-- Randomization and frozen AI releases (.claude/TASK_SCOPE.json
-- note2026_09_28_rct_backend, M4; Protocol V9 p.9, p.18).
--
-- ai_releases: what an AI arm runs -- the exact model snapshot (never an
-- alias), the prompt document versions and hashes per session, the memory
-- algorithm and index versions -- the exact strings the runtime sends and records. Frozen before enrolment; a frozen release
-- cannot change (a change is a new release, logged as a protocol deviation,
-- with re-consent).
--
-- randomization_lists: the allocation sequence generated by the independent
-- statistician, stratified by site x diagnosis (stratum = '<site code>|MDD' or
-- '|ANXIETY'), uploaded as a file (the hash of the file is kept). No role can
-- read it -- not through the API (the store never returns entries) and not
-- through Supabase (RLS on, no policy). An entry can only go from unused to
-- used, once.
--
-- allocate_participant(): the only way to allocate. In one statement it
-- takes the next unused entry of the participant's stratum (FOR UPDATE SKIP
-- LOCKED: two allocations at once never share an entry), marks it used,
-- writes the allocation with the study's current frozen release, and moves
-- the participant to 'allocated'. Allocations are append-only.

CREATE TABLE IF NOT EXISTS ai_releases (
  id text PRIMARY KEY,
  study_id text NOT NULL REFERENCES studies(id),
  label text NOT NULL,
  model_id text NOT NULL,
  prompt_versions jsonb NOT NULL,
  memory_algorithm_version text NOT NULL,
  memory_index_version text NOT NULL,
  status text NOT NULL CHECK (status IN ('draft', 'frozen', 'retired')),
  frozen_at timestamptz,
  created_by text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION tbct_guard_ai_release() RETURNS trigger AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    IF OLD.status <> 'draft' THEN RAISE EXCEPTION 'ai release % is % and cannot be deleted', OLD.id, OLD.status; END IF;
    RETURN OLD;
  END IF;
  IF OLD.status = 'draft' THEN
    IF NEW.status = 'frozen' THEN NEW.frozen_at := coalesce(NEW.frozen_at, now()); END IF;
    RETURN NEW;
  END IF;
  -- Frozen or retired: only frozen -> retired, nothing else.
  IF OLD.status = 'frozen' AND NEW.status = 'retired'
     AND (NEW.model_id, NEW.prompt_versions, NEW.memory_algorithm_version, NEW.memory_index_version, NEW.frozen_at)
         IS NOT DISTINCT FROM (OLD.model_id, OLD.prompt_versions, OLD.memory_algorithm_version, OLD.memory_index_version, OLD.frozen_at) THEN
    RETURN NEW;
  END IF;
  RAISE EXCEPTION 'ai release % is % and cannot be changed', OLD.id, OLD.status;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS ai_releases_guard ON ai_releases;
CREATE TRIGGER ai_releases_guard BEFORE UPDATE OR DELETE ON ai_releases
  FOR EACH ROW EXECUTE FUNCTION tbct_guard_ai_release();
DROP TRIGGER IF EXISTS ai_releases_history ON ai_releases;
CREATE TRIGGER ai_releases_history AFTER INSERT OR UPDATE OR DELETE ON ai_releases
  FOR EACH ROW EXECUTE FUNCTION tbct_record_history();

CREATE TABLE IF NOT EXISTS randomization_lists (
  id text PRIMARY KEY,
  study_id text NOT NULL REFERENCES studies(id),
  list_version text NOT NULL,
  stratum text NOT NULL,
  sequence integer NOT NULL,
  arm_code text NOT NULL CHECK (arm_code IN ('CLINICIAN_ONLY', 'AI_CLINICIAN', 'AI_LED')),
  upload_sha256 text NOT NULL,
  uploaded_by text NOT NULL,
  uploaded_at timestamptz NOT NULL,
  used_at timestamptz,
  used_by_participant text,
  UNIQUE (study_id, list_version, stratum, sequence)
);
CREATE INDEX IF NOT EXISTS randomization_lists_next_idx ON randomization_lists (study_id, stratum, sequence) WHERE used_at IS NULL;

CREATE OR REPLACE FUNCTION tbct_guard_randomization_entry() RETURNS trigger AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN RAISE EXCEPTION 'randomization entries cannot be deleted'; END IF;
  IF OLD.used_at IS NULL AND NEW.used_at IS NOT NULL
     AND (NEW.id, NEW.study_id, NEW.list_version, NEW.stratum, NEW.sequence, NEW.arm_code, NEW.upload_sha256, NEW.uploaded_by, NEW.uploaded_at)
         IS NOT DISTINCT FROM (OLD.id, OLD.study_id, OLD.list_version, OLD.stratum, OLD.sequence, OLD.arm_code, OLD.upload_sha256, OLD.uploaded_by, OLD.uploaded_at) THEN
    RETURN NEW;
  END IF;
  RAISE EXCEPTION 'randomization entry % can only be marked used, once', OLD.id;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS randomization_lists_guard ON randomization_lists;
CREATE TRIGGER randomization_lists_guard BEFORE UPDATE OR DELETE ON randomization_lists
  FOR EACH ROW EXECUTE FUNCTION tbct_guard_randomization_entry();

CREATE TABLE IF NOT EXISTS allocations (
  id text PRIMARY KEY,
  study_participant_id text NOT NULL UNIQUE REFERENCES study_participants(id),
  study_id text NOT NULL REFERENCES studies(id),
  stratum text NOT NULL,
  randomization_entry_id text NOT NULL UNIQUE REFERENCES randomization_lists(id),
  arm_code text NOT NULL,
  arm_id text NOT NULL REFERENCES study_arms(id),
  ai_release_id text REFERENCES ai_releases(id),
  allocated_by text NOT NULL,
  allocated_at timestamptz NOT NULL
);

DROP TRIGGER IF EXISTS allocations_append_only ON allocations;
CREATE TRIGGER allocations_append_only BEFORE UPDATE OR DELETE ON allocations
  FOR EACH ROW EXECUTE FUNCTION tbct_refuse_rewrite();

CREATE OR REPLACE FUNCTION allocate_participant(p_study_participant_id text, p_allocation_id text, p_actor text)
RETURNS SETOF allocations AS $$
DECLARE
  sp study_participants%ROWTYPE;
  site_code text;
  v_stratum text;
  entry randomization_lists%ROWTYPE;
  arm study_arms%ROWTYPE;
  release_id text;
BEGIN
  PERFORM set_config('tbct.actor', p_actor, true);
  SELECT * INTO sp FROM study_participants WHERE id = p_study_participant_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'study participant % not found', p_study_participant_id; END IF;
  IF EXISTS (SELECT 1 FROM allocations WHERE study_participant_id = sp.id) THEN
    RAISE EXCEPTION 'participant % is already allocated', sp.study_code;
  END IF;
  IF sp.status <> 'enrolled' THEN RAISE EXCEPTION 'participant % is % -- only enrolled participants are allocated', sp.study_code, sp.status; END IF;
  IF sp.diagnosis_stratum IS NULL THEN RAISE EXCEPTION 'participant % has no diagnosis stratum', sp.study_code; END IF;
  IF NOT EXISTS (
    SELECT 1 FROM (
      SELECT DISTINCT ON (consent_type) consent_type, status FROM study_consents
      WHERE study_participant_id = sp.id ORDER BY consent_type, decided_at DESC, id DESC
    ) latest WHERE consent_type = 'main' AND status = 'granted'
  ) THEN
    RAISE EXCEPTION 'participant % has no current main consent', sp.study_code;
  END IF;
  SELECT code INTO site_code FROM sites WHERE id = sp.site_id;
  v_stratum := site_code || '|' || sp.diagnosis_stratum;
  SELECT * INTO entry FROM randomization_lists
    WHERE study_id = sp.study_id AND stratum = v_stratum AND used_at IS NULL
    ORDER BY list_version, sequence
    LIMIT 1 FOR UPDATE SKIP LOCKED;
  IF NOT FOUND THEN RAISE EXCEPTION 'randomization list for stratum % is exhausted or missing', v_stratum; END IF;
  UPDATE randomization_lists SET used_at = now(), used_by_participant = sp.id WHERE id = entry.id;
  SELECT * INTO arm FROM study_arms WHERE study_id = sp.study_id AND code = entry.arm_code;
  IF NOT FOUND THEN RAISE EXCEPTION 'study has no arm %', entry.arm_code; END IF;
  IF arm.ai_enabled THEN
    SELECT id INTO release_id FROM ai_releases WHERE study_id = sp.study_id AND status = 'frozen' ORDER BY frozen_at DESC, id DESC LIMIT 1;
    IF release_id IS NULL THEN RAISE EXCEPTION 'no frozen AI release for an AI arm'; END IF;
  END IF;
  INSERT INTO allocations (id, study_participant_id, study_id, stratum, randomization_entry_id, arm_code, arm_id, ai_release_id, allocated_by, allocated_at)
    VALUES (p_allocation_id, sp.id, sp.study_id, v_stratum, entry.id, entry.arm_code, arm.id, release_id, p_actor, now());
  UPDATE study_participants SET status = 'allocated', allocated_at = now(), updated_at = now() WHERE id = sp.id;
  RETURN QUERY SELECT * FROM allocations WHERE id = p_allocation_id;
END;
$$ LANGUAGE plpgsql;
